spring.application.name=UpiSimulator

# PostgreSQL Database URL (replace 'mydb' with your database name)
spring.datasource.url=${DB_URL}

# PostgreSQL Credentials
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

JWT_SECRET_KEY=${JWT_SECRET_KEY}

# Hibernate properties
# 'update' automatically creates/updates database tables based on your Java Entities
spring.jpa.hibernate.ddl-auto=update

# Optional: Displays SQL queries in the console log (great for debugging)
spring.jpa.show-sql=true

